<?php

namespace AppBundle\Repository;

/**
 * CommentpostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentpostRepository extends \Doctrine\ORM\EntityRepository
{
}
